[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.18"
syn = { version = "1.0.95", features = ["full", "extra-traits", "visit-mut", "parsing"] }
proc-macro2 = "1.0.39"